---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: rfspager-stash-repo
  namespace: rfspager
spec:
  backend:
    rest:
      url: "${REST_SERVER_URL}/rfspager"
    storageSecretName: stash-secrets
