---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.6.4
      sourceRef:
        kind: HelmRepository
        name: grafana-loki-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      image:
        repository: grafana/loki
        tag: 2.5.0
        pullPolicy: IfNotPresent
      replicas: 3
      persistence:
        enabled: false
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        distributor:
          ring:
            kvstore:
              store: memberlist
        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
        memberlist:
          abort_if_cluster_join_fails: false
          # Expose this port on all distributor, ingester
          # and querier replicas.
          bind_port: 7946
          # You can use a headless k8s service for all distributor,
          # ingester and querier components.
          join_members:
            - loki-stack-headless.monitoring.svc.cluster.local:7946
              # max_join_backoff: 1m
              # max_join_retries: 10
            # min_join_backoff: 1s
        schema_config:
          configs:
            - from: "2020-10-24"
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: index_
                period: 24h
        storage_config:
          aws:
            insecure: false
            s3: https://${SECRET_MINIO_ACCESS_KEY}:${SECRET_MINIO_SECRET_KEY}@${SECRET_MINIO_ENDPOINT}/loki
            s3forcepathstyle: true
          boltdb_shipper:
            active_index_directory: /data/loki/index
            cache_location: /data/loki/index_cache
            resync_interval: 5s
            shared_store: s3
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
      extraPorts:
        - port: 7956
          protocol: TCP
          name: loki-gossip-ring
          targetPort: 7946
      serviceMonitor:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http-metrics"
    promtail:
      image:
        registry: docker.io
        repository: grafana/promtail
        tag: latest
        pullPolicy: Always
      serviceMonitor:
        enabled: true
      extraScrapeConfigs:
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            label_structured_data: true
            labels:
              job: "syslog"
          relabel_configs:
            - source_labels: ['__syslog_connection_ip_address']
              target_label: 'ip_address'
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'app'
            - source_labels: ['__syslog_message_SRC']
              target_label: 'source_ip'
            - source_labels: ['__syslog_message_SPT']
              target_label: 'source_port'
            - source_labels: ['__syslog_message_DPT']
              target_label: 'destination_port'
            - source_labels: ['__syslog_message_DST']
              target_label: 'destination_ip'

      syslogService:
        enabled: true
        type: LoadBalancer
        port: 1514
        externalIPs:
          - 172.31.0.3
        externalTrafficPolicy: Local
