---
apiVersion: v1
kind: Service
metadata:
  name: external-vcsa
  namespace: networking
spec:
  type: ExternalName
  externalName: vcsa.devlan.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vcsa-ssl-ingress
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" #important
spec:
  ingressClassName: nginx-internal
  rules:
    - host: vcsa-ssl.devlan.io
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: external-vcsa
                port:
                  number: 443

  tls:
    - hosts:
        - vcsa-ssl.devlan.io
      secretName: vcsa-ssl.devlan.io
