---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-authelia
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.2.0
      pullPolicy: IfNotPresent
    postgresqlUsername: postgres
    postgresqlPassword: ${SECRET_AUTHELIA_POSTGRES_PASSWORD}
    persistence:
      enabled: true
      size: 2Gi
    commonAnnotations:
      prometheus.io/probe: "true"
      prometheus.io/protocol: "tcp"
