---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sentry-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://sentry-kubernetes.github.io/charts
  timeout: 3m
