---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 10.3.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    query:
      enabled: true
      replicaCount: 2
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: "thanos.${SECRET_CLUSTER_DOMAIN}"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-response-headers: X-Vouch-User
          nginx.ingress.kubernetes.io/auth-signin: https://login.${SECRET_CLUSTER_DOMAIN}/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err
          nginx.ingress.kubernetes.io/auth-snippet: |
            auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
            auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
            auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
          nginx.ingress.kubernetes.io/auth-url: https://login.${SECRET_CLUSTER_DOMAIN}/validate
        tls: true
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      strategyType: Recreate
      persistence:
        size: 30Gi
    storegateway:
      enabled: true
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    objstoreConfig: |-
      type: s3
      config:
        bucket: thanos
        endpoint: ${SECRET_MINIO_ENDPOINT}
        access_key: "${SECRET_MINIO_ACCESS_KEY}"
        secret_key: "${SECRET_MINIO_SECRET_KEY}"
        insecure: false

  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: thanos-query
            patch:
              - op: add
                path: /spec/ingressClassName
                value: nginx
