---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-nfs-kasten
spec:
  capacity:
    storage: 1024Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/kasten
    server: "${HOME_NFS}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-nfs-kasten
  namespace: kasten-io
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
