apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:PCBce6D5c/7WjW+EickOGgGuorKxZX9rtT8s,iv:B7NrbGm0A6xyUfCkBHy679XTK4y4YzFh1Z7fQwaCCYo=,tag:vZuPRjMgHJoKMBOj88YYSA==,type:str]
    SECRET_AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:f1lqNqjExgVs6EacgdFrZPnvvLc6Z+mSh+smaw==,iv:bo7ZDZHV7XKBFd2Oks2qjvMiSexQOjIsiB5g5G6ZZo4=,tag:i4EJq/jRWNoXwEAgeM4NrA==,type:str]
    SECRET_AUTHELIA_SMTP_EMAIL: ENC[AES256_GCM,data:PK9WCZhq8mZdu4xAZsPYdbM=,iv:6BqWT3NAToSu1r4CRwiCHndX65yXJmZdY2svDB/nQYg=,tag:ox9aB+HvAGCojdL+xtav2A==,type:str]
    SECRET_AUTHELIA_SMTP_SENDER: ENC[AES256_GCM,data:vvbDZ7ajuqTTEeGEL7i2,iv:+CVB3YtbtbTQyShOAno2K0dQ9zxvCzxuW0WF1UM31P0=,tag:D63Wqgj0b9CPLkj0Z+ZScg==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:RFV9RZcoSyF8X1/5aNk4bia0pYdD2P1q2NpTPrzE66FSY420oDAE80vGpJfBXMuGyGpuds+usZWfYIH8J4Au5uDq+dmNODccdv53pyXRt4uHxPOJ32/y5HIA,iv:aLVUiJ1RGgGlSdZH7GNKy+fd+JPTJ+gCdsDpqqBZNkg=,tag:O7rqzf00PPQugebiuswMDg==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:PCTHNI4r0H9/1z1vUEfdsEgVnqktUiS0s6CWbw==,iv:Rjsohsmw4otPlN4zCC4sK+wys70uZv/qh451H6Tgrio=,tag:VNCpjZVCztQFyC1j6jI4Eg==,type:str]
    SECRET_AUTHELIA_USER_NICK_EMAIL: ENC[AES256_GCM,data:mGCIHpPsKKP0LOYDkYPpbtM=,iv:PpeS6Vux2E1U5DrGVxCJCyxzeGAzq5gI7JmdZAZpR/g=,tag:LBgSXwS+AlnZWPJjBthUfg==,type:str]
    SECRET_AUTHELIA_USER_NICK_PASSWORD: ENC[AES256_GCM,data:OgC1GRe0OFe5967LylvSKRK51zmQngYFF7WhcB9Eex1o/MR9RmYfKMz+2jruKlnVt5jJil7vzNecJUyJR67uE0/ZgXqRBEeRrMTMnMh5K1XiSYV3m6d2yKrso1//W9yz+Q==,iv:rLSYD07K48sloOjrEqVYc4UsMJ8/pdyaj+l8mqJ0z40=,tag:WBEcdr7xlU/Xg8zozXNrYA==,type:str]
    SECRET_CLUSTER_CERTIFICATE_DEFAULT: ENC[AES256_GCM,data:tc2IzSVp6QXbKKTwv1KPCWSfKug=,iv:ZbgrkCuahtUfwNPxKF1HEC1FY6ElUml0D2KJqi1AOYE=,tag:m2XKXwri5RPhxGNRc3wpRw==,type:str]
    SECRET_CLUSTER_DOMAIN_EMAIL: ENC[AES256_GCM,data:YdpGeuOjmnj8C5uE26jslqs=,iv:4TkPNRXOCae6wOQOjTDYg6kxJywAU1SlLvOWcqqf+k4=,tag:uCLVQJ2qtRDYhFh2Q1cLDQ==,type:str]
    SECRET_CLUSTER_DOMAIN_ROOT: ENC[AES256_GCM,data:ugnN1esERRkv/HuRe01j,iv:S2YVSE0JBpBQC5cZAoe9otYkrX8QKL/c9Hg+wGhH2wU=,tag:BLyV8Kq5VKkgMx/z7qmQkg==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:k0mUti/H9PnYXHgwQDv0,iv:HFoS+YDTgVs3OW+CUJZJpYHC3TvWfAw8iiHEsW6WYUw=,tag:5TKS5mvw0vjQ1NNHjRopqQ==,type:str]
    SECRET_CLUSTER_CF_EMAIL: ENC[AES256_GCM,data:Xg2XmXXYVELux2Zp8a1NOWH7,iv:BSmBGwEWVG+kCZturiOxtjs8wxzXldyqJQY8hCXyuTs=,tag:LtPO0GYXpOe0Ox51UChVsg==,type:str]
    SECRET_CLUSTER_CF_API_KEY: ENC[AES256_GCM,data:wIfQkLLZpy/ge4oYpE9krNQuWu7fGC1oynMenFPJxPChnGgP0g==,iv:BmV57wTEK5TRWzgNktb8+yh7ENHWxlGwxUie738idHg=,tag:plUntLjM8csJUFzjg+tC+Q==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:vLXmdHV+7qRqwxhClzZZf8oJc9QX0+eMiZk5wr0dKQ9bdyu49GkEuZ4C6g==,iv:SwQC9Xk40EXgeHmboPgyYq+BKd8Nqwu+xerQ+N2d7rQ=,tag:G6rsCmQex+vLKlNfWMnfmQ==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6fVPLGBEOqTMRA2aws1F6X1k5ZDgBT1LfUx1f68cnQ==,iv:fi609sigTWfZjzSAUfp4iQizK69We4vr0ccqnC5qg3g=,tag:oC4EGOISYNZ4XCpMVG5JWw==,type:str]
    SECRET_BOOKSTACK_DB_PASSWORD: ENC[AES256_GCM,data:1Kb8KtlgmvHVkpSUxmNJCdjw+6G6VzeFYpHIQaO9mZT/,iv:bh27iI+UdkNaU1PYsk8OnQDnuOfyAXsS85JLy6vI97I=,tag:9u2Diys9yXyBMa3O7AKviA==,type:str]
    SECRET_BOOKSTACK_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:m60YIWPSsqcU65cdTaY9aIAcf1HelgRhqC/aF/QnDKDtjOQNqD0=,iv:bW/4UuUtVfx8Zc171cQ86CsQDUCF4Lz1qg/BfBcxHjE=,tag:yH5YjAE3/H2h1QneZkGWfg==,type:str]
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:MWi3ZOk/AnqHNYk=,iv:ilToN0XnNKwWXdrEvWeNcAkUYeOkpHgGQAqt4uVy+O4=,tag:CLsiFSuQyIk7mwyBMTDKVQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:NqogRg==,iv:xGW5QewdIX2YkNGOYhY9VEUgnu9Hp0bv0of4Ds9h1EA=,tag:oUq1yf5XKLAkm1xvrt1SfQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:jFqMmhsAuWN1ENY8LNV0ysfKoD7A4k96oq9gf6PVWtt2Mm1zxoW1jp8DQEKG2IVEdWZIh6mZ1pjukQaEuS5Y5Oja9V4ygPN0AskhxPA6v9A=,iv:3Moprk9Xczv7mmAadmZ6OFlYvDwt7I8P/wh3r+IyMZE=,tag:mRwKKspb7tx4BQ+LPgSv4g==,type:str]
    SECRET_HASS_LATITUDE: ENC[AES256_GCM,data:2O45ioF9fxGb8g==,iv:wYcsvSPBNiZC4sYQW9j8iGcEx8kTjP64vs1Dn1Cv66g=,tag:XP/QaDdUZmcojo9vQb1NQw==,type:str]
    SECRET_HASS_LONGITUDE: ENC[AES256_GCM,data:N3SGwk21eu3ZxQ==,iv:KyuxVPyz0/lhlqNbs2hasYWBXYu60qZQ4qt0BJF0elA=,tag:oWHfm8Awnn5jwNxnlr9nYA==,type:str]
    SECRET_HASS_ELEVATION: ENC[AES256_GCM,data:/GI=,iv:qPrZS32A8Gtv0vOC69s8VaISYuCfNFZHyNHaTY5Ed54=,tag:fqlwMqX+PWSFG463VGIxoA==,type:str]
    RFSPAGER_DB_PASSWORD: ENC[AES256_GCM,data:3RBRzRsJgYusO/5h2lreqAD2bzlE5yc=,iv:Ew575MaKtLZSB3HfaKoZZN9nCcNPl138TDI9j4c1D8o=,tag:5B2nreYJDxiyLr4C0rFCHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-24T06:00:04Z"
    mac: ENC[AES256_GCM,data:B7hHgasgUofVtLdzq/rF35koC4J3BMXLEoNw9/q5myR/Ar4I/rt6FInMvRUPgzMPY++TdGAMU+/Q36ANUJQnDAoU2idawrBWtQl9rjoUc/mOZGX/W4pVrHsfetdJo09wbd1gmvgl4hX07L4swnLlVvaZ/w4SIUQOQgwE1LSV2Mw=,iv:5ClmIOHMD2S80UVCwLi5Rs+KW/3s5KnY0TLuFttOyCM=,tag:4VcZcAr4tmX+2k82Fha4Cw==,type:str]
    pgp:
        - created_at: "2022-02-24T06:00:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cARAA31RQfSHNue+QrvRBJOKGVHd/aF/ikQ5ePTwGx1E6YLpB
            i8opa0SblXYBqOFmdsR8wWS8ck4IjbJRubl8WEpvnoa0AOWXXaaXVPKCO0eX/rVO
            mf9I+deG2kiFAH3yw2WkJ6asjaiuhV+wqmSz86iqnM6GNQKb4KnNFcGocm4wLOdz
            Cs+SaNPkUQ+ENO5YzAA+6BHG7MZw/GyGOyLMrwlHUJgQeXqr9oEzEmPig64OUBHS
            KMrgQaPZSxIVgqfK/VYmK+FvP4s0yFU2EX8B24LNUyZx7hlhMQ9yYO9wRXL5hOTJ
            vMAYV7yK0pYhqs3J2OVPxC5UAfBqRvTXKntuQGT77344WRhX08c74JeNvEx0+fp9
            Bu2iSUpZmBM7IViK6LpXuGYLcf21JkSrM5xBUJGiQFxuJAI3IdqQbqVL3WzVTgsX
            sgIQtuStZ71qQXWsXw9WC0VXeLIxFVcpd7Ld5dDQKNkeWeNeYRG1vBkepzfaXI0H
            Bo/vt8Z10u2PxDCvQB01YIkdha31xpQ51msSd1+8h9X0x8gK/g0E1LS5S9AMir7y
            I7lG8Ry4M3qqveRhaTstog5UyJeSaGJCSYPc5tMZQV8wrIi5J+LCJ5WZh46HDv3n
            N7ljEjcK6RRWEtDyzeb9xXUVrEVYv1d+QmjxMyEsnVbdqGk0v6dGao1AepZOjCHU
            ZgEJAhCotGlLK/iWZ9c1qm4lBHdWI+C2reqhVlRIN9IN2vFXAsbBZpRbESdpooUs
            9ZITTzOcH6wDRI40ZpExLSXCsJ5djxw27Dizwc75Xrkeglc0RRann3DFpxSr3zcq
            UDhMy2xOmA==
            =dtxO
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
