apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:m6Fk3h2g+hOvx76sLNyPTZYZKYCI6YmYouNz,iv:86i/HT9x38y2B2B0epx7HiKM6Q/geeBkV6EhkWhCeT4=,tag:TKkRMV/uV+gE9uPSj2O8Fg==,type:str]
    SECRET_AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:20C/T3nhOg5kw0V/dxwyhHnI+ZNfNUu5uGR97w==,iv:oclkvGL7hD6Iv4xlGQh86Tjhh6m6enUVrSCsK9p5Phs=,tag:0sZN20jx7SBp4sfrmWicoQ==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:uRaJEqnfUoiAsqgX/mc3U403/quzHPe18+E=,iv:fOrga576HzwN/QLi6yRMnCHQZeQaI+9Sdwcxrfn0KBQ=,tag:E6kD5irMwtZ05MNz8g8HJw==,type:str]
    SECRET_AUTHELIA_SMTP_EMAIL: ENC[AES256_GCM,data:WgFBkk16/0jqnFguHZfiIiw=,iv:2YsmRFijrs2+0rxEEqcHctaquX6E9bp2F3DpLLF3NxE=,tag:GEJeOPoOqkSuTFKGmZverw==,type:str]
    SECRET_AUTHELIA_SMTP_SENDER: ENC[AES256_GCM,data:+m+ewQDd7zjLkECExCuj,iv:i8nCjDVKh/JjdLb+zL+c05NQL2sy6WjjCEVplQkVqVs=,tag:hmnx09MxZjI5ga+iCjiDkA==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:nlkDe0/HuclPpyseKwQzDZWvE+ibn2tuzMHF+McBWfvLt1eHQvGL7lEGDTBKmmfCIV4gVuXhboGXno7Eo+gdpNsHieQj0wNPzxatYtgrGzH8VNZ2xYmyNRzQ,iv:zX8l/QR9uKGUILsFdlx+yNcqz8okIf5tR9miB9Zr+M4=,tag:Uo8PAB4g2KsU2qJp+knjyw==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:6g7e+2Uurpn6uixU9rZxV/zxRfFhVcXBGqv0mA==,iv:OWb/k5QNmL4W8vIGO7Oaj5JaBmGR9S+sIwracY72W/w=,tag:7eJRO6WIWhQz5yEbd3q/sQ==,type:str]
    SECRET_AUTHELIA_USER_NICK_EMAIL: ENC[AES256_GCM,data:w0MWa0p9oj/lL/sfmKQncP8=,iv:KzLBnM+j/RfnSIps08T5UrcLIfoufRpKBG6Egw99+7E=,tag:gEBrnNzBIztoFC35pJlTvA==,type:str]
    SECRET_AUTHELIA_USER_NICK_PASSWORD: ENC[AES256_GCM,data:8SOq8jncgmimXk0WeKMbv/GLivWOMwpS+saDU9lro9+l0IoFZ8dWk9uwY8OE2BIxahwJo4Wlo//RaPq0qK/pp3Oh4a4cvz+Fwny48Y0zbMJK0A+UGcB2DmPsEWazXemYAw==,iv:FzAfoAuvCAs6SzH+NZefooUpdmwIiHjPOQKKUJCxWHg=,tag:ej6h9DJMwagrTmj4YAjp2Q==,type:str]
    SECRET_CLUSTER_CERTIFICATE_DEFAULT: ENC[AES256_GCM,data:45LrJWOGTnnD+uo+54kCRF2+9z4=,iv:ZWt/ej+aDnvl5jQ6CwqqTeFdc1Zp8/sziBD+hUrkDIk=,tag:rRHqLcjlsYcscuHrwGQDsA==,type:str]
    SECRET_CLUSTER_DOMAIN_EMAIL: ENC[AES256_GCM,data:p+TXXme45ypy1vIfY1EWHe8=,iv:Pgsq6Ic1zOKZ8i9NB0vAqc0KHORAONsitU8avrrYJsI=,tag:cbRKyCtfMXGSO5cDGRmFaA==,type:str]
    SECRET_CLUSTER_DOMAIN_ROOT: ENC[AES256_GCM,data:PaFNzLY5P3w5Nf4OOack,iv:DAxf4M1GV1fhohlerKOuiZTntJ8ai+w+rBXUEceOgXs=,tag:dQOdaEHgGfQWpc/89FwJ4A==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:bTiz0BB43fKjJySsm8V0,iv:QFVeXljm6tgyLZb4QMsYYqXqI74BNq0ge/4fspeJePU=,tag:9C1JIcjqW1QjUdEvDujvqw==,type:str]
    SECRET_CLUSTER_CF_EMAIL: ENC[AES256_GCM,data:BEyiIeNqWVvA7orX1yPslF0s,iv:CbDGBCQuScZrZrUFRjfqKdBaQ+2pX/ZnVuYDH++xvUc=,tag:bYZydB33G/4N3DRigR9phA==,type:str]
    SECRET_CLUSTER_CF_API_KEY: ENC[AES256_GCM,data:oq4OnbS4szwLPjLZcktMCAZrWzsSsALUbFbXgEjpfge46AmM6g==,iv:6JJrxirrCML0GeEb4G5QbxOidVhjKBqTJf7n4N2seZU=,tag:mu2nirUUsoIH4vkMm9X7QA==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:H4IvwXziMfRzi0mxuzR+XBGU/UtLU1XkqOKPQe17mhqaHSVXwhlhNTIM1g==,iv:lgUxwLDudTI0bMwWKR2zMpsV0S7t7XCehbbe/hpV4d4=,tag:BFo7kNikTJIJtmXnr/Ga6A==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:a+YSu87WxwSvXDGytifuuc42RgOBn3EgAucYkLFJWA==,iv:/PRWKw4V190ew9zJVcAafLqiS0CpFFtIgIZizHGvJYY=,tag:jAad3R70ONp5wp5cVJ9ClA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-22T04:15:03Z"
    mac: ENC[AES256_GCM,data:XrI6abVyh5I9XGnEOSl1NcZThM3Snjpo5FyHYSH5DKiqmPewM/puVUm2PKICXqaaDa39vmiJVCPWjAG0MCdTNaXZ5dLHvOua7JD9jrEMOwFCq5DYqSnELHCNspxFe4VyfFWQwlQ4oY5I9lXzMNzIRWSOeOaPEs6/6IwCtDpLohQ=,iv:AWbMNxg26UetG71B5l1dOusDPxjr/nrjlA+Ho/bGOAQ=,tag:wUxB4l5QHO3E/bBSXHHtBA==,type:str]
    pgp:
        - created_at: "2022-02-22T04:15:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ//TlNsREx8tM/24qctErvyHSedBlsyM6kFHii0XH8JKeOx
            3xOcWk4ttSP5SpWsRNxlvvmnWMSYXiMLIoC3nsIlifo7ngXbKr+wBTQaLQLLqP5a
            2S4EsvEyhcLqKLGRO+91JRHDCJmW6lvbHo59W6Np7JSY8zpBkeck33N3Q8NcfFKE
            wmgPLpfxct365OoAgr27JnCZNioCjbv3yJdaEtTP2nbFqzdq8qRlVcLzAG/iTcO7
            TDxTTudF4U+PkKusAAJbJCEXpT+6NuMDkHBVB2AhBKgmv58+FQOODX666heBknhO
            JJshclAF2IgF2tX7+FWtQH+MhX0divGr8gpw8KsVRZQ8+mzMrfuIytnDImGLT77W
            Om9g44g1/SP2kMCSFo5ALDrFS/zah6LseW/jByO8qAcrYzqpCyXB2SgNNKbya/PE
            HINnhQKZ4UrBFxDfv8ThpHdLoeIaTlGT2V9QL7Z9EsXhbbL2HHUDJRLIytCT0UkP
            NSci4ShKyLyogIRzVmXvnnUWMxAA1QXmBsDHbVG4q3LI8qcSEn+V/Bj2jYy7Frk3
            Crq26Qu6IJXSwBDlHDShmcCPzWPaplDqgvevjuBAfj8I2NwclOg/RvoaynMS+QYA
            diTmOKW+qj+3ptzbialjfav+FP5vOP9X/8T3y5C0ZMJ2zuAZFqqLTGUyFARnMpjU
            aAEJAhD+GfuejmeSlGT++nwzEwU5+LXI8jVTfkdJnh/+lvaBwmfZsmiVfFCn/IiL
            pWD/8spTdB2bueDVR/7MSQuTlDw8kKEUmN63NphGfS0r2ue7B2ikcnxIDK5839NU
            XVBVMLYvn/Hi
            =w7D5
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
