---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.appscode.com/stable/
      chart: stash
      version: v2022.02.22
      sourceRef:
        kind: HelmRepository
        name: appscode-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      license: "${STASH_LICENSE}"

    features:
      community: true
