---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia-config-custom
  namespace: networking
data:
  users_database.yml: |
    users:
      Nick:
        displayname: "Nick"
        password: "${SECRET_AUTHELIA_USER_NICK_PASSWORD}"
        email: ${SECRET_AUTHELIA_USER_NICK_EMAIL}
        groups:
          - admins
