apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forever-secrets
    namespace: wordpress
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:CxeoTJhv9XbMO6HWzHcDCC31tJ/CiGzJ0A==,iv:I3oWvqzxKw/OPjuvCKfoMDyMbSjGasZdCR95xHVsaYE=,tag:oStXhxb1ozD9Y+km59zlag==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:y4PIwh+Bz7ta4QpsyKCGWA==,iv:nryChz+HV1YGRiKRIlrc777krR22ZW7YMbNtWEv7gwg=,tag:RtUtDSTzSvXcjZ5Vd6p1Vw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:eYPvqNwXx9T2P5CmUbNl79IIn7/44hj2IBxPNLiMBOOGl26csACZ8tPs3V9WZKEmanplKiWeweASEYFXjw==,iv:EvBm5Bb+OFO9L4Amw0weNoOMAlivgZUWMULbApTpDVE=,tag:Zx3qfe1PljJIAZDZiGrUqg==,type:str]
    AUTH_KEY: ENC[AES256_GCM,data:kXB1F36LDNJgvMq41tRhhVgOUmPDaOkDQAmHg9Ag4yLkutGYvjHkQzOs5T2+o1TNlNdrkTknp7i4qB5kTSYT3A==,iv:sjde5UGaftl4CiSLBoAWYPBIC/jGXjP9LxawvFkz4so=,tag:VjUyRWxLFIozxEGdQn23kw==,type:str]
    SECURE_AUTH_KEY: ENC[AES256_GCM,data:0PsrOEikdzzkGAl7wjUz9kCYNP9i2Xuz2TX0cxdgRyWJmZA3DZahAzzP3Vaae5yYNk3pLI1Nat+Rz4xb/fhg+Q==,iv:KcBGjrzc9E7pckq1GTNN3qgqchgVYHeLd1tkkqwaMzs=,tag:ONyNAYFKTSBUQbcaCwoRIQ==,type:str]
    LOGGED_IN_KEY: ENC[AES256_GCM,data:jP9mdwxSKKYSTDXqIUdJ53EteYUbFqYs6pHcji3Uvav165kPJ10P2R9DFnh4SQ1pkGcUgRjXuhik1a7NX3Qwtg==,iv:XSbVq65Lyhlnr/mDq4cly40YIodN6a98xxDqw7BdBZY=,tag:SoNcTAtxxHGuVugbVtVKDA==,type:str]
    NONCE_KEY: ENC[AES256_GCM,data:BwPky32o3T3XLUNTskX5YERQjJI0y3ScDQaJoEJfI8SSJUJSmQLHf4z7ByTOlD0gKcC+p4yyA+0kM27L5A8fKg==,iv:Fe+ZVoUsQmT0rlXO4dNX5IS5+X5GkWR+9q6DZJSVIAk=,tag:rscixBcAehWjx5fnFsXpAQ==,type:str]
    AUTH_SALT: ENC[AES256_GCM,data:KRxaf/CPfmU2DmnvLn5odHgC5PXd0Cljdrme3sMnEoMgGzyxnoM86uyb2KlN9eTfOuRsqGZ/MmS3LZCXWi+R2Q==,iv:AqH7+cFvGY07BgHkuTwe6RgtbYSWk+Z42oQrYa/a4bU=,tag:5O1Kjnq9hxk0w3X9rlVYQw==,type:str]
    SECURE_AUTH_SALT: ENC[AES256_GCM,data:iaSeH4XfIdCPA0gvljf47U+zkLxgQ7U68iPTwhlbo8X2DArZZdBUEl/Wv1kjM52LeTPMdtJCOme5bGEc+mDkSQ==,iv:WIY7g7jAM5+z65aNCnNzJiFM2opo91MijsopDmSIVDw=,tag:+VdlvZl5r5+n+qUE1AJaAg==,type:str]
    LOGGED_IN_SALT: ENC[AES256_GCM,data:Yj+9b43Y/qEEKR9I0j4jto1zKXVcwVzQpTzq/7cjM9DaK7gkySL3Fqea6B9eHHXp1kpTTAO2QWV3JDAd6yJruw==,iv:iQ5Ofkw8Gm9wjWjY5J1i9gpWfDat6y5PIVFIDEIGs+g=,tag:9bMdJ8WR+4pO6+/wGelsJA==,type:str]
    NONCE_SALT: ENC[AES256_GCM,data:AGukyM3+RJzbJaIAm7UZT+j/+KVD9Zd/Hh68yljF88HtcHw2QXgUyTzBRGBL87bWAzBqBLKXB5XywQ3wBpwliw==,iv:clU/CtuJkcnqGlet2Yp8PQ6oxNIFcr8/sX+nvIvYt4k=,tag:QjGOKESDsHesBx0ypRtceQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T06:33:20Z"
    mac: ENC[AES256_GCM,data:hq2yQLBM00hdMCG8SMFTsqe5QByQVF57taMimDJOJpIBTd32ANX0lXpL2IfrFhCD2z6XYs2qo3vXR65fVSMC7BI7ns1qYS2VxnUeXz40VaCCg+CUibzCYtWnnEPIYMntarP1owyBVyzWWMHTE5eHhMp5NTbkSinhSbLHAe9JW3g=,iv:yD7rC4dtkXEFt9PDCWxScwXPM4lxGxFzvKyI0R7K3ls=,tag:EUrhrHqz+zHBGguzv6CCZQ==,type:str]
    pgp:
        - created_at: "2022-03-17T06:33:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ//VAFzCDPf3bsIffqOJqXCxR00LeJcAP+aRYQP4+q3jXl6
            fyEEir2QwLUZPxtxaZ3jh/YpzhaSNbvVi76TXN3DsamHGUWwhEaE5wpHhiVFP+cG
            lyAKjJ7d4pOecqaSI59KUyux32jZtygRFjfl0BdEhN11noYx9DprLYrTnIZERlpu
            wc64lb13lvZIty4qxA+ZEAvOdz2xnUzE/xHIarK7aw8OHnwdvj9CoYwDH9QJeG+Z
            /OUHTUExNUBozZWbd+a6yH1M0sCAsv0axUokhoCZH0ayHyH78bsdZfCb71uRO2Ci
            lmCbItjFPOdbexQOMsTgD1r66RCbYzW1Bal/G3X6pU1CtvCFOM8Ga66b+YOsY3TO
            OzKMW/bWFV6XjwIZYs7CvbK1s+EoPIxtm8q3B+a7HXIAZ05u4Lsy+aNjDwZQINxA
            MNwNpbWI6gPM4Y1OauJ3JZdrvzRf1T3z4RFlfYjnTdN4sNDmg/r7Z0NB8fEE1X1G
            dp+3enU1KAn5x43yhpWtb0W0xXd6Q84vzDCMPEjZLl4m0C/t19rlmUzy9hsBF1iz
            T9RhoXAQxlAmTMuIuUIU0JBUn6SEs4FR69PcUb/v6o9MjK4gdiMCCXadTYMfzSPS
            sPjdD2iZe4/MyORXeJ2D3KaFCAaJsJQQbN9PlzybxJ8UmK+q1nO4VgEUHhrPQKnU
            ZgEJAhBmgVF1zJrp1BHgQxelpZSgr+rq1V6G7qcfTJPDZAb5wZrbEswRYCEizJbH
            Q0hhdK3TluPCByizmW2N5WQUWzIGYBzMboDtgtSWMkgRzbwDmyN5ruS+/rj8oIL0
            cFrvYTeLQQ==
            =HLPn
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
