---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rfspager
  namespace: rfspager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicko170.github.io/laravel-charts/
      chart: rfspager
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: nicko170-charts
        namespace: flux-system
      interval: 5m

  values:
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 15

    image:
      repository: docker.io/nick170/rfspager
      tag: main-a1c594b-1645684683

    schedule: "*/1 * * * *"
    scheduleCommand: /process/cnb/schedule

    workerMin: 3
    workerMax: 10
    workerCommand: /process/cnb/worker

    envFrom:
      - configMapRef:
          name: rfspager-config
      - secretRef:
          name: rfspager-secrets

    imagePullSecrets:
      - name: regcred

    env:
      TZ: "Australia/Sydney"
      PORT: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"

        hosts:
          - host: "rfspager.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "rfspager.${SECRET_CLUSTER_DOMAIN}"
            secretName: "${SECRET_CLUSTER_CERTIFICATE_DEFAULT}"

    postgresql:
      enabled: true
      postgresqlUsername: postgres
      postgresqlPassword: "${RFSPAGER_DB_PASSWORD}"
      postgresqlDatabase: postgres
      persistence:
        enabled: true
        size: 15Gi
