---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rfspager
  namespace: rfspager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=http://charts.npratley.net
      chart: laravel
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: npratley-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/nick170/rfspager
      tag: v1.1.5

    imagePullSecrets:
      - name: regcred

    web:
      enabled: true
      count: 3
      command: /cnb/process/web

    cron:
      enabled: true
      command: /cnb/process/schedule
      schedule: "*/1 * * * *"

    worker:
      enabled: true
      count: 5
      command: /cnb/process/worker

    env:
      TZ: "Australia/Sydney"
      PORT: 8080

    envFrom:
      - configMapRef:
          name: rfspager-config
      - secretRef:
          name: rfspager-secrets

    volumes:
      - name: secret-files
        secret:
          secretName: rfspager-secret-files

    volumeMounts:
      - name: secret-files
        mountPath: /secrets/

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - host: "${RFSPAGER_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - "${RFSPAGER_DOMAIN}"
          secretName: "cert-${RFSPAGER_DOMAIN}"

    redis:
      enabled: true

    postgresql:
      enabled: true

      global:
        postgresql:
          auth:
            postgresPassword: "${RFSPAGER_DB_PASSWORD}"
            username: postgres
            password: "${RFSPAGER_DB_PASSWORD}"
            database: postgres

      primary:
        extraVolumes:
          - name: pgbackrest-config
            configMap:
              name: pgbackrest-config
        initContainers:
          - name: pgbackrest-restore
            image: bitnami/postgresql:14.2.0-debian-10-r22
            securityContext:
              runAsUser: 1
              runAsGroup: 1
            volumeMounts:
              - name: data
                mountPath: /postgresql
              - name: pgbackrest-config
                mountPath: /etc/pgbackrest
            command:
              - id && ls -lah /postgresql/data

        persistence:
          enabled: true
          size: 20Gi

      readReplicas:
        replicaCount: 0
