---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rfspager
  namespace: rfspager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.npratley.net
      chart: laravel
      version: 0.0.2
      sourceRef:
        kind: HelmRepository
        name: npratley-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/nick170/rfspager
      tag: v1.1.4

    imagePullSecrets:
      - name: regcred

    web:
      enabled: true
      count: 3
      command: /cnb/process/web

    cron:
      enabled: true
      command: /cnb/process/schedule
      schedule: "*/1 * * * *"

    worker:
      enabled: true
      count: 5
      command: /cnb/process/worker

    env:
      TZ: "Australia/Sydney"
      PORT: 8080

    envFrom:
      - configMapRef:
          name: rfspager-config
      - secretRef:
          name: rfspager-secrets

    volumes:
      - name: secret-files
        secret:
          secretName: rfspager-secret-files

    volumeMounts:
      - name: secret-files
        mountPath: /secrets/

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - host: "${RFSPAGER_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - "${RFSPAGER_DOMAIN}"
          secretName: "cert-${RFSPAGER_DOMAIN}"

    redis:
      enabled: true

    postgresql:
      enabled: true
      postgresqlUsername: postgres
      postgresqlPassword: "${RFSPAGER_DB_PASSWORD}"
      postgresqlDatabase: postgres
      persistence:
        enabled: true
        size: 15Gi
