---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - configmap.yaml
  - secrets.yaml
  - secret-files.yaml
  - regcred.yaml
  - pgbackrest-config.yaml
  - helm-release.yaml
  - backup.yaml
