apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rfspager-secrets
    namespace: rfspager
stringData:
    APP_KEY: ENC[AES256_GCM,data:VyWt6ilMWgI2cN2upjdCWfNoFaId1TvrH+O01UtPQiY9C7ihjVgC0426vvrBdZvG/7Wv,iv:LvtazheQv/U+vsAfEgP+tdwcDBgb18LKo1XK514Ta4Q=,tag:x216Bu89jRFgvVDivUinmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zQEeaR+LkF6Cbh4TkCbG605o3gRORQYf,iv:gIkUP7IUnqDaGbyoo6Wbj8aVsz58Pz80cu5vEnuxTfI=,tag:wWlMrFeZeMFuVqii41nOmg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:t+aIcnwGin2oCeUyY8W0KvxYqUbTPjk=,iv:1bORf3Mu3gF5wDM2/nrRV1w0BBMPAu7SswlcKDfBE+Q=,tag:x8fs8kA6rffMm3Hb3CCuVA==,type:str]
    PASSPORT_CLIENT_SECRET: ENC[AES256_GCM,data:HldP6/CygIgUbGkRCD5Y8AnfmwgKWjnPqEVwEuPGqsQgOs1TVugbZw==,iv:86QtqoT4uUHFwAVOcYo39N99wCiMzyTFF/1lDp77Frg=,tag:ZPt9W2f6qjdS1ISocMi1zA==,type:str]
    REVENUE_CAT_SECRET_KEY: ENC[AES256_GCM,data:YJ+vn7lEhbEwXe1+EnlKZKvoXloe4DQ0CmtKdX7hsNw=,iv:8aCdNB104mY0h3GJLqJmR5d+OP3KxLFphQOlocb4Cnk=,tag:c+uTC9bIs4CckF3LD3BVxA==,type:str]
    ADAPTY_SECRET_KEY: ENC[AES256_GCM,data:EWdKZqloz4P5IKeIwe4KpkAM1NBWd1YgcpWZOtc6I6ySmUaINbGWLOAb3RxPzAyS24cmnQs=,iv:4FM29mbakYS+c6jSAW7gwMjc/YLBCRHi3B/3MSm7wJw=,tag:xC/QrwhQsv3xjfIP7X/RJQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:eewQcU7P+RT6RNynLRdLkstLmjKXJ9ah,iv:5BrGEdt/MMwqjo+Nr3Fm93hM9Aoy1AzHkW1w/pIIMw0=,tag:ZVoC3aVZ3kbLhPjo1xooTA==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:XAJrJfr4wwY2gVRIf/WxuUguoTvVk8z/sB80XzAzAT6GWPUrBHETTQ==,iv:K5XpM5mt2Tk1nEtOIQFrfFox7mPAYhmnWRbWi3FLP+U=,tag:VY8dkQDiSC59w9Msrl9pPg==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:jL+E+Pe3okp/axGJ/yttNV63R4bsMuIVbm+B3oA7r6YtxYa9ouIXoA==,iv:AzqzXnA2I/+Xwndkerqj6oZxWrVmzBk+96PZ2HYMlbk=,tag:AVoikSVgZvH/b8MFDdIN2w==,type:str]
    MIX_PUSHER_APP_KEY: ENC[AES256_GCM,data:I7aUUchNgVmDtAeE0rFNk4k/izT1mXbcKJidYK5UHLUZOtKFG8l1sg==,iv:H0Mo4x1qt/RkejeTewF1bR8IcZfe3y+ClnKoS5wIu5Y=,tag:ANQMoaEA9vyZTqGU5DFmIw==,type:str]
    MIX_PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:tUgO0x+/vlaVI+xpYdyOd1GCSKqdmdBFYjftB842BvVe1so5YLuYcw==,iv:z1uwj0a8uIv3WxJYICzJtCke8LR1IOIsi5cBX1JHC4A=,tag:nj3fPa3O4ytdqNJ3h0hZvQ==,type:str]
    APN_PRIVATE_KEY: ENC[AES256_GCM,data:BgzYpWyJKRNnnnsJ9JDrDcz/tdezFKtiRrdlZ1taV8DW/rrugUs5cmYMZX3MuGQ+lO/hS5AFAmyvQKRC3t7R9z1g7nU3OkL3XZeZp8Vjk81N4VCdDG4XxlcnKHB6gReu9x6MM/tR6dO4/xociRyazGUw3GPWHspSfTCpxu/6zI+tM2Zhp93Dj12xdm4lw+VGa3seRSXy6C7LOYUocQ2PjO55aNCTjZCQh4r0NoFpWw3UynQkft4HDT179y8GxoofJKGa0h9sVloR0iQnzVSi+OV3KMkUhSk24LTPXbWgV6nS78SrhJuezcjZRjhbtjlsmMtBNQG5KpiclNhY,iv:wX57Z8LIEiQogoavy1fnxgJimVxQ2cQV/ifYwZc6dgA=,tag:O5kQlCfaht7QMQIzf2gMZQ==,type:str]
    SENTRY_LARAVEL_DSN: ENC[AES256_GCM,data:kG3rOjzfmrBgKBWuYBlBf3dRFKq4MwAR6JXXE6mCbBX30fel/vLi+3Y2lxKqupciedRnK35mGLz9TkcuweUesSg=,iv:wdWC4C1M3b9q1rWa6pWo/83BMbtFyYke+8MEUVsevA8=,tag:lqJsARhgnCATyuGnO2lTrw==,type:str]
    FLARE_KEY: ENC[AES256_GCM,data:WTLk8K9/hC3sGZW/FkUUsAwqKpPqGBqUumSr69CrfUjPhmBj,iv:N/o6xYYpUVn9wC6nOBihM0C02/5zM9pMSHRgDiDPR+Y=,tag:5mhf7s3M/w8IFrySLqCgSQ==,type:str]
    FACEBOOK_CLIENT_ID: ENC[AES256_GCM,data:QeFFKlyVseY/IfifK8QC,iv:5M6nK867Z6w3bAPqR1GjZz7GSeR/BL2tew2gTv6wpPU=,tag:2vGXmdt7sRF66dfUCNWuog==,type:str]
    FACEBOOK_CLIENT_SECRET: ENC[AES256_GCM,data:k+WRKXH+hsGLtU7WsrTfdXaPCYpQyLAzfWL67hDbUS4=,iv:1lReZn4x9JDiEvScogLMAWDF4VQB34aDdTfZEb7VIeU=,tag:aGNyKgqbyO7DM2D9sxE3PA==,type:str]
    APPLE_CLIENT_SECRET: ENC[AES256_GCM,data:ARexHhfYYacilFqPTUSEB2+JuGBE+jBCZblAJbON1P3G1GanWx2DqkUOcOOtG1VCOwqmIHxYhkdcqWxgleny8GUibb4guxgPxdC43WCwfhCQ5Rwpeoh4ZllbjSmQAI8lx/yFSO44E//2xePdkqRs0UQDdbfM+umaX0XjLNplS3t23Izz0nVlLwQAgXLP7bzMr+aI0vcDfbQzCzHnz26fp869lMVCv41YetiLzdsp81eK5wohEYjkcOdW58P0WPgnxcj1D8cSebG2o8HFFRX+Ot2LyTjZEUYOhAvUo/nkU/tpDgR2t2VMPwA1d8n4cAxlEe3wCqRqs/9+mWoYBi2zw3NM/HiNd5pssHiRVxjjoR1WAkgLYkrcb+vS6/TTz17PsNqW0TM9gJoLTSI/05d2Jag84CYfgqdFC4010/pW0zIZlA==,iv:0rISvHI088uFCjTzKTkCYkXBtJtoaA373s46/PB7f6U=,tag:2GIVaPhpfuRVx5lQVjzMCw==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:3ez8s0ktClcAIQglZufjZXdmPdYBs+KLNu+bWmkPvfm6vS1PPbsFYpfBp+oT7Dv2l8HP4V6nJzZ1Xo0lptgsJ9wVAV07AlVES9JqJxpmThtS0bnCzEV896RGWIyZmRL50vN4UfkNDTTQ5A5RuZzkuK3cOXtJ7vHMwp54DitYBAhX0dgy3yDRR2wCmT1VwlgRBaO3Nha0TADSmSjaTVdK5MB5AC63AMJbj0mRjtZFi9wNiqt05uJAzAEFEOUBWR4TY07ZNiikPAA2EZi0pvNKHvxrECss+TbsBwa3wUhVawUpDBmiiTjI8+yhgiu6ERGcqYKDlWvQbEyt0weK,iv:ztvM2O9HefKJkkvi0pxsEPjBf49dwwRqH3vosAkdGaI=,tag:Pv2SIJ+wBPBkcM7dF1qq9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T11:22:23Z"
    mac: ENC[AES256_GCM,data:YdzTUyaLI+Thn/7xWA6bI+zjdrOEynExv4VPv8DWQUhdMMOnrPBx/rhMyshAHRaIvedApaic3hvLXClY8UmBo03udnSEQrGmOoIkArSrAG2+hn6kSArV2dtePLgZO+8InBtmsKd5eLJH7gspK6xSDLMcGO5D2CMmjwAMzJ0AZtQ=,iv:wQBp7rJzLJDx/Lz7hnvLESgx4JLhqv+v/wPBKKIeAzQ=,tag:QmDFEAmP08mTNGzNo38/gQ==,type:str]
    pgp:
        - created_at: "2022-03-04T11:22:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ/9E1L9bTD/eh7p/BrGV5EdwKt3zDmqdl7DYw+t2r3z5ILj
            ICt0/9Dg6aDSIIOChlhEoIDTZy1eCqQbaCeTf5amgAclLu5gtfbVFJ/+PXPGC4PU
            WpcoX67FkkD5zwSOtBmElCvpQNHMuycnjkAv7mKIIb6n4DqvUWGHVQ3+qFgQDOPK
            8DPHUQk8OFWnqZdcFoh7I03l5f6un/zBktjfMSM02zQJssg1XdhE+0mG/VXIVrRn
            74q269OOWUXe/GtE46GNM3LIblQZdd9gOVezXHaZrEgOhHmbuZLnJBnX1OUIE31S
            hKkKreRTKgzKasfstPxtOFY2Mm9gcg7imlR0B0u5D5DFGww4e9Y8WwgZcS8CNf96
            WMCYIEKqcYoY9CJVQ5qwQ0m95pOdqv08Gmr+u7ys3o8XKdLDzh+9enSl814kWt6m
            k49k4b9b0XB+LzHW5F9gXBi55gMcf0YMx3fsjaOdzvKtFHUcJ06Rmsu+YnUBmGWm
            qaHydTKL9CnC8O6MELhYRc2DJPTsAldkfR9jJFOvlhN8neN+wsy1LrpAh/xJiNPS
            mqQkHexCO5N9sUQP5PFSWJAj+8UOS0W3hHqDjfP5EIaweNYLkph2YxvheEW+rSA6
            mj0q+ZKyJUISeStA2hS+NJVw0UDIhkO+0jvFCaAz5GHm1kI0Ii40B6SRlnaYYyrU
            ZgEJAhBc5nz+9ST0l7jd/dL2620NXxTeAbRJUaTYBPdSXvTaEsrHCY/336HMq78h
            RIQcEhqEhqxlKBg9BDgwyHnQJ8l2bugIhJXMRcqwIOpaWX00c9Yk73ZHdV7Irqjh
            ogswSNqYGg==
            =mh36
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
