---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: benji-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/elemental-lf/benji
  timeout: 3m
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
