---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-${RFSPAGER_DOMAIN}
  namespace: networking
spec:
  secretName: cert-${RFSPAGER_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${RFSPAGER_DOMAIN}
  dnsNames:
    - ${RFSPAGER_DOMAIN}
    - "*.${RFSPAGER_DOMAIN}"
