---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-coder.devlan.io
  namespace: coder
spec:
  dnsNames:
    - 'code.devlan.io'
    - '*.code.devlan.io'
    - '*.dev.devlan.io'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: code.devlan.io
  usages:
    - digital signature
    - key encipherment
