---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  releaseName: coder
  chart:
    spec:
      chart: coder
      sourceRef:
        kind: HelmRepository
        name: coder-charts
        namespace: flux-system
  interval: 5m
  values:
    coderd:
      devurlsHost: "*.code.devlan.io"
      tls:
        hostSecretName: code.devlan.io
        devurlsHostSecretName: code.devlan.io

    ingress:
      enable: true
      host: "code.devlan.io"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx
