---
kind: Secret
apiVersion: v1
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:SlAR+EwWT5tqoHcVvmjH/ni+Yoz+/8qkb9TawaAMrv5OYD2OwQ==,iv:WJwR6D7CrOYlqvj3ijrT7UYzhI2BSG5vnV41tpS555k=,tag:1VQ4jEXzTCtkbPZXz4QKLg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T07:17:23Z"
    mac: ENC[AES256_GCM,data:QMZIe1njYzzbk1gxnc2QeExfmxs110+XW8+gcG6oaYBQoSzHvWCyXRSrC49wdbAcCbsN2jezSBQS6orN2hHB/Y1sGKC+Awdwtoev39ul0fuYzQWJulXGsUmZkDZ2aK4ESrRry3eN3k4HXGtEcATj8cdvwHp8gHrcDx9/GD+OO0o=,iv:2ShAl5QbM+wb1V4aViuD+59d8fyZ5+E8FF0hocK+9cA=,tag:eUzL2Tf1Agu8JBqSqkCnIw==,type:str]
    pgp:
        - created_at: "2022-02-15T07:17:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ//T8jaLkle/2cn/K8fuomL+izj31L9v+mUosCUs4u0TYW+
            xA+PHThESUrlZ8kQpqSQVFd3edB78inb/N/+d+90faSk3kbEA0hMhkfvAjLvpPU9
            W9Igd4GoLLrL3My2BkKqkmPKUl8yadP52XjR29RsNcsNes27OBnE0ErCBhUTShjV
            p//cQuhp9/31r3axqWGnHzy779bPTfiHDjbN15mQ35WUAf9llAAmhY7u2Ga/mZio
            MWE1GDo/5h3zP2zjDxNJQXy7eXtoPBRwerjqV8HTMNnXmkFogZImrWvB439fqO5x
            Mt7ACl8Pfp6GxvxNm9E216FnV7ew8g13bP+wCn6YZL6PmTsU4KN55mF5ckX0Sli4
            gZlR6mhbqPEg0LGJAAnWHDthw7fDfkcnOVnGAV8g+zisfc3KJU1128WYgQBF4x/D
            76yJR4+HaVGTPFul8dt69VaF0j5J4SjZTG+/Ue0QPxZyPZSMPLJbROvA6t0p8C3g
            xH56kDYNrdJ0x578om7XdesMqV2ppLhXtDIY4i3dKUDU4uy8R1uOexElYLn7YbUf
            Yj2LIcWi+6/nubYAnciC7M5PrwzkPs77jIMqmUULJTuDFdg+p0P4iLde1kFQiAsS
            cQZiiHog+ozexbJIkBDI0yuWX8qi55fA/x+7N7eni6ieo4jIg5YB+AzsAgWgdorU
            aAEJAhBUHiTkkPJ1VjhhnGyFNBREH0dRrJomYKrQDnMHvi61UjO+x/i5E0uBvgrz
            CHPQI6DMeBDGXvNZXBD5HBiyqbhNxJ1FokbQXfNx2qj9bbflAHpOtyNVLiGxNRLI
            LjdeUUmCeU6g
            =v16i
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
