---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: home-nfs
  namespace: kasten-io
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: home-nfs-kasten
      path: fusioncloud
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
  type: Location
